# musicbot docker-compose!
# 2021-04-10
version: '3.4'

services:
  musicbot:
    build: musicbot
    container_name: musicbot
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:5000/health']
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    stop_grace_period: 3s
    env_file:
      - '.${MUSICBOT_ENV:-dev}.env'
    volumes:
      - type: bind
        source: ./musicbot
        target: /musicbot
      - /musicbot/src/musicbot.egg-info    # make sure the egg-info is there for pip install
