# musicbot docker-compose!
# 2021-04-10
version: '3.8'

services:
  musicbot:
    build:
      args:
        - 'MUSICBOT_ENV=${MUSICBOT_ENV:-prod}'
      context: '.'
      target: prod
    container_name: musicbot
    env_file:
      - '.prod.env'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:5000/health']
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    stop_grace_period: '${DOCKER_STOP_GRACE_PERIOD:-3s}'
    volumes:
      - type: bind
        source: ./logs
        target: /musicbot/logs

volumes:
  logs:
