# musicbot docker-compose!
# 2021-04-10
version: '3.8'

services:
  musicbot:
    build:
      args:
        - 'MUSICBOT_ENV=${MUSICBOT_ENV:-dev}'
      context: musicbot/
      target: ${MUSICBOT_ENV:-dev}
    container_name: musicbot
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:5000/health']
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    stop_grace_period: 3s
    env_file:
      - '.${MUSICBOT_ENV:-dev}.env'
    volumes:
      - type: bind
        source: musicbot
        target: /musicbot
      # used in dev
      # - type: bind
      #   source: tools
      #   target: /tools
