# musicbot docker-compose!
# 2021-04-10
version: '3.8'

services:
  musicbot:
    build:
      args:
        - 'MUSICBOT_ENV=${MUSICBOT_ENV:-dev}'
      context: '.'
      target: dev
    container_name: musicbot
    env_file:
      - '.dev.env'
    volumes:
      - type: bind
        source: .
        target: /musicbot